name = "nusantara"
main = "index.js"
compatibility_date = "2024-04-03"

[[durable_objects.bindings]]
name = "VOICE_ENTERPRISE_ROOM"
class_name = "VoiceEnterpriseRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["VoiceEnterpriseRoom"]
